# Webserver default port
PORT: 3000

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/public/**/*"
    - "!src/public/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    node_modules:
      - "node_modules/foundation-sites/scss"
      - "node_modules/motion-ui/src"
    project:
      directories:
        - "src/public/scss/**/*.scss"
      main:
        - "src/public/scss/app.scss"

  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/public/js/app.js"
  static:
    - "src/{views,routes,bin}/**/*"
    - "src/app.js"
  www: "bin/www"

